#! /usr/bin/env bash

# From el-repo

alias gis="git status"
alias giss="git status -s"
alias gib="git branch"

gia(){
    if [ "$1" == "" ]; then
        git add .;
    else
        git add "$@";
    fi
}

giam(){
    local first_arg="$2"
    git add "${2:-.}" "${@:3:}"
    git commit -m "$1"
}

gip(){
    git pull origin $(git branch | awk '$1=="*"{ print $2 }' )
}

giP(){
    if [ -e "$1" ]; then
        git push origin $1
    else
        git push origin $(git branch | awk '$1=="*"{ print $2 }')
    fi
}
